### ISSUE TITLE
Doc/tutorial?

### ISSUE THREAD

**Issue by hughperkins** [Rod-Lin/ink#3]
Might be nice to have at least ~50-100 lines of doc/tutorial going over the first initial steps, so I can see what this does?  (It sounds potentially interesting :-) )

**Comment by zhengyao-lin** [comment]
Eh..actually it did have a tutorial but the grammar is constantly changing so I removed it temporarily.
Honestly this project was not well-planned at the beginning and it's really just a little try to build a interpreter...
But if you're really interested in it, some testing examples are available at /examples dir (files with suffix .ink)
Thanks for paying attention to this little project :-)
